export enum ENDPOINTS {
    login = '/auth/login',
    register = '/auth/registration',
    checkEmail = '/auth/check-email',
    confirmEmail = '/auth/confirm-email',
    changePassword = '/auth/change-password',
    feedback = '/feedback',
    loginGoogle = '/auth/google',
    training = '/training',
    trainingList = '/catalogs/training-list',
    tariffList = '/catalogs/tariff-list',
    userJointTrainingList = '/catalogs/user-joint-training-list',
    usersAcceptingJointTraining = '/catalogs/training-pals',
    newTariff = '/tariff',
    uploadImage = '/upload-image',
    userMe = '/user/me',
    user = '/user',
    invite = '/invite',
}
