export enum PATHS {
    root = '/',
    main = '/main',
    auth = '/auth',
    login = '/auth/login',
    register = '/auth/registration',
    confirmEmail = '/auth/confirm-email',
    changePassword = '/auth/change-password',
    result = '/result',
    resultErrorLogin = '/result/error-login',
    resultSuccess = '/result/success',
    resultErrorRegister = '/result/error',
    resultErrorUserExist = '/result/error-user-exist',
    resultErrorNoEmailExist = '/result/error-check-email-no-exist',
    resultErrorCheckEmail  = '/result/error-check-email',
    resultSuccessChangePassword = '/result/success-change-password',
    resultErrorChangePassword = '/result/error-change-password',
    achievements = '/achievements',
    profile = '/profile',
    feedbacks = '/feedbacks',
    calendar = '/calendar',
    settings = '/settings',
    training = '/training',
}
